joint_velocity_example_controller:
    type: franka_example_controllers/JointVelocityExampleController

joint_position_example_controller:
    type: franka_example_controllers/JointPositionExampleController

cartesian_pose_example_controller:
    type: franka_example_controllers/CartesianPoseExampleController

cartesian_velocity_example_controller:
    type: franka_example_controllers/CartesianVelocityExampleController

model_example_controller:
    type: franka_example_controllers/ModelExampleController
    arm_id: panda

force_example_controller:
    type: franka_example_controllers/ForceExampleController
    arm_id: franka_emika
    joint_names:
        - franka_emika_joint1
        - franka_emika_joint2
        - franka_emika_joint3
        - franka_emika_joint4
        - franka_emika_joint5
        - franka_emika_joint6
        - franka_emika_joint7

joint_impedance_example_controller:
    type: franka_example_controllers/JointImpedanceExampleController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    k_gains:
        - 1000.0
        - 1000.0
        - 1000.0
        - 1000.0
        - 500.0
        - 300.0
        - 100.0
    d_gains:
        - 100.0
        - 100.0
        - 100.0
        - 100.0
        - 50.0
        - 30.0
        - 10.0
    radius: 0.1
    acceleration_time: 2.0
    vel_max: 0.15
    publish_rate: 10.0    
    coriolis_factor: 1.0

cartesian_impedance_example_controller:
    type: franka_example_controllers/CartesianImpedanceExampleController
    arm_id: franka_emika
    joint_names:
        - franka_emika_joint1
        - franka_emika_joint2
        - franka_emika_joint3
        - franka_emika_joint4
        - franka_emika_joint5
        - franka_emika_joint6
        - franka_emika_joint7
    pos_error_max: 0.5
    rot_error_max: 0.5
    k_p_nullspace: 50.0
    k_ext: 0.95
    filter_gain: 0.95