controller_list:
  - name: franka_position_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - franka_emika_joint1
      - franka_emika_joint2
      - franka_emika_joint3
      - franka_emika_joint4
      - franka_emika_joint5
      - franka_emika_joint6
      - franka_emika_joint7
