controller_list:
  - name: joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - franka_emika_joint1
      - franka_emika_joint2
      - franka_emika_joint3
      - franka_emika_joint4
      - franka_emika_joint5
      - franka_emika_joint6
      - franka_emika_joint7
      
  - name: franka_gripper_node
    action_ns: gripper_action
    type: GripperCommand
    default: true
    joints:
      - franka_emika_finger_joint1
      - franka_emika_finger_joint2
