joint_names:
  - panda_joint1
  - panda_joint2
  - panda_joint3
  - panda_joint4
  - panda_joint5
  - panda_joint6
  - panda_joint7
arm_id: panda
# [Joint position, Joint velocity, Cartesian Pose, Cartesian Velocity, Torque]
rate_limiting: [true, true, true, true, true]
# [Joint position, Joint velocity, Cartesian Pose, Cartesian Velocity, Torque]
cutoff_freq: [50, 100, 100, 100, 100]
internal_controller: joint_impedance
