joint_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - franka_emika_joint1
    - franka_emika_joint2
    - franka_emika_joint3
    - franka_emika_joint4
    - franka_emika_joint5
    - franka_emika_joint6
    - franka_emika_joint7
  constraints:
    goal_time: 0.01
